apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-sfchinesemedia-com-tls
spec:
  secretName: k8s-sfchinesemedia-com
  issueRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: sfchinesemedia.com
  dnsNames:
    - k8s.sfchinesemedia.com
  acme:
    config:
      - http01:
        ingressClass: nginx
      domains:
        - k8s.sfchinesemedia.com
